Mobile version of the Portfolio project
Stanleeeeee/Stanley-Portfolio pull request #1
Opened 2022-03-18 17:16 UTC by Stanleeeeee

In this mobile version of the portfolio project, I created 
- Tne Navigation bar
-  The header and added a background image. Please review my project.

2022-03-18 22:01 UTC, JuliCarracedo commented
Hi @Stanleeeeee , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that has linter errors in it. Please solve them and submit your project for a new review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-03-19 16:39 UTC, Stanleeeeee reviewed
The linters corrections have been made correctly. This is the mobile version of the portfolio project. Please kindly review

2022-03-19 17:44 UTC, vic778 requested changes
### STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @Stanleeeeee , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Descriptive commits and correct use of the Git Flow :fire:
- [x] :white_check_mark: page titles :white_check_mark: text headings :white_check_mark: basic structure of the page 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


![so close](https://c.tenor.com/nMbdSNsg_jsAAAAC/the-simpsons-homer-simpson.gif)

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 17:44 UTC, vic778 commented on index.html
> +    </nav>
kindly as is required in the project requirement you're working on the mobile version. of which only the hamburger should appear. be sure to add hamburger instead of all the links. please follow the design of the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A848) template you have chosen

2022-03-19 17:44 UTC, vic778 commented on index.html
> +           </div>
kindly as is required in the project requirement You must stick to the design as much as possible (e.g. font, colors, images, tests, margins)according to the design of the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A848) model you have chosen

2022-03-19 17:44 UTC, vic778 commented on style.css
> +}
kindly refer to this [link](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A848) to visualize the design of Figma. it is important to know that you can inspect each element in Figma to see the styles that suit it

2022-03-19 17:44 UTC, vic778 commented on style.css
> +  }
kindly the background image should be at the right end of the project please fix that

2022-03-22 09:54 UTC, closed without merging