Form validation
Stanleeeeee/Stanley-Portfolio pull request #12
Opened 2022-04-15 14:09 UTC by Stanleeeeee

This form validation doesn't accept uppercases in the email. it was made possible using 
- Javascript

2022-04-15 14:26 UTC, brytebee requested changes
Hi, @Stanleeeeee & @felixodette 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request

![](https://media.giphy.com/media/OQeKGexhYKVjLaSzPd/giphy.gif)

**_You have submitted a project, that has failed linters. Kindly fix linters errors._**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-15 15:10 UTC, Stanleeeeee reviewed
This is the form validation using Javascript. All linters errors have been corrected

2022-04-15 15:56 UTC, codepantha requested changes
Hi @Stanleeeeee 👋,

### STATUS: REQUIRED CHANGES ♻️  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/xNJPkAQnLGVGjYpsBW/giphy.gif"/>

### To Highlight 💡 
- Meaningful commit messages ✅ 
- Professional README ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 15:56 UTC, codepantha commented on index.js
> +});
- [ ] Your form submits even when the user enters an uppercase email. The correct behaviour should be an error that tells the user to make sure to email is lowercase only. Please fix this 🙏

2022-04-16 10:47 UTC, Stanleeeeee reviewed
Form validation using javascript. I made corrections requested by the reviewer

2022-04-16 11:05 UTC, AnselemOdims requested changes
### Hi @Stanleeeeee , 
Good job implementing some of the changes requested by the previous reviewer.

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-16 11:05 UTC, AnselemOdims commented on index.js
> +    errorMessage.classList.remove('hidden');
- [ ] Good job on making it work but please remove the HTML validation and make sure it only uses the Javascript validation with the error message appearing close to the submit button

2022-04-16 17:28 UTC, Stanleeeeee reviewed
Made corrections to the email validation
- It uses lowercasing only for validation
-  It throws an error if you do otherwise

2022-04-16 17:36 UTC, smunozmo approved these changes
Hi @Stanleeeeee, 👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 👏 👏 👏 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-09 06:48 UTC, merged